version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=yokudlela
      - POSTGRES_PASSWORD=yokudlela
      - POSTGRES_DB=yokudlela
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - ./psql-create-multiple-db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql-data:/var/lib/postgresql/data
